In [1]:
import crypto_trading_backtester as ctb

In [3]:
ctb.load_crypto_data('fmp','BTCUSD')

2024-07-30 11:46:47.843 | SUCCESS  | crypto_trading_backtester.data_loader.loaders.fmp_loader:fetch_all_cryptos:36 - Request for fetching cryptocurrency list was successful
2024-07-30 11:46:49.479 | SUCCESS  | crypto_trading_backtester.data_loader.loaders.fmp_loader:fetch_crypto_pricing:85 - Request for BTCUSD pricing data was successful

,date,open,high,low,close,adjClose,volume,unadjustedVolume,change,changePercent,vwap,label,changeOverTime
0,2019-07-31,10089.970,10497.00,9881.00,10405.94,10405.94000,16631520648,16631520648,315.97,3.131530,10218.4775,"July 31, 19",0.031315
1,2019-08-01,10404.410,10670.00,10321.42,10533.01,10533.01000,17165337858,17165337858,128.60,1.236010,10482.2100,"August 01, 19",0.012360
2,2019-08-02,10533.620,10922.08,10500.00,10820.76,10820.76000,17489094082,17489094082,287.14,2.725940,10694.1150,"August 02, 19",0.027259
3,2019-08-03,10822.090,11089.74,10572.00,10977.51,10977.51000,15352685061,15352685061,155.42,1.436140,10865.3350,"August 03, 19",0.014361
4,2019-08-04,10977.980,11950.00,10977.98,11819.49,11819.49000,16530894787,16530894787,841.51,7.665440,11431.3625,"August 04, 19",0.076654
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1822,2024-07-26,65794.200,68333.00,65705.60,67921.49,67912.06250,30488630457,30488630457,2127.29,3.230000,67346.2400,"July 26, 24",0.032300
1823,2024-07-27,67914.700,69529.00,66624.30,67899.40,67813.33594,34691905492,34691905492,-15.30,-0.022528,68124.7000,"July 27, 24",-0.000225
1824,2024-07-28,67912.900,68443.00,67021.80,68244.30,68255.86719,18043166945,18043166945,331.40,0.487980,67815.6200,"July 28, 24",0.004880
1825,2024-07-29,68246.880,70162.00,66240.20,66755.88,66755.88000,41302944690,41302944690,-1491.00,-2.184720,67719.3600,"July 29, 24",-0.021847
1826,2024-07-30,66786.766,67179.00,65846.38,66778.00,66778.00000,40571199900,40571199900,-8.77,-0.013125,66601.1300,"July 30, 24",-0.000131